
[server]
port = 9000

[database]
uri = "localhost:27017"
dbname = "gv"

[cache]
uri = "localhost:6379"
password = ""
database = "0"

[app]
paths = [
    "/Users/sickyoon/Movies"
]
user_expiry = 86400 # one day
